name: ETL
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.Jupyter
    container_name: jupyterlab
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./DataLayer:/home/jovyan/work/DataLayer 
      - ./Transformer:/home/jovyan/work/Transformer
    networks:
      - imoveis-network

  imoveis.dos.sonhos.db:
    container_name: imoveis.dos.sonhos.db
    build:
      context: .
      dockerfile: Dockerfile.Postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ImoveisDosSonhosDB
      POSTGRES_USER: usrImoveisDosSonhos
      POSTGRES_PASSWORD: S3nh@F0rte
    networks:
      - imoveis-network

  pgadmin:
    container_name: imoveis.dos.sonhos.pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: imoveis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    depends_on:
      - imoveis.dos.sonhos.db
    networks:
      - imoveis-network
networks:
  imoveis-network:
    driver: bridge