services:
  imoveis.dos.sonhos.db:
    container_name: imoveis.dos.sonhos.db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: imoveis.dos.sonhos.db
      POSTGRES_USER: usrImoveisDosSonhos
      POSTGRES_PASSWORD: S3nh@F0rte
    networks:
      - db-network

  pgadmin:
    container_name: imoveis.dos.sonhos.pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: imoveis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    depends_on:
      - imoveis.dos.sonhos.db
    networks:
      - db-network
      
networks:
  db-network:
    driver: bridge
